[project]
name = "support-copilot"
version = "0.1.0"
description = "Area Screenshot Tool - Visual area selection with periodic screenshots"
requires-python = ">=3.10"
dependencies = [
    "pyautogui>=0.9.54",
    "mss>=9.0.0",
    "pillow>=10.0.0",
]
